// @praxis/kernel — Kernel Diagnostics
// Helper functions for gate reason codes and diagnostic construction.

import type { Diagnostic, DiagnosticSeverity } from '@praxis/contracts';

/** SchemaGate reason codes. */
export const SCHEMA_REASON_CODES = {
  SCHEMA_PASS: 'SCHEMA_PASS',
  YAML_PARSE_ERROR: 'YAML_PARSE_ERROR',
  PLAN_FILE_EMPTY: 'PLAN_FILE_EMPTY',
  PLAN_ROOT_NOT_OBJECT: 'PLAN_ROOT_NOT_OBJECT',
  PLAN_SCHEMA_INVALID: 'PLAN_SCHEMA_INVALID',
  PLAN_SCHEMA_LOAD_ERROR: 'PLAN_SCHEMA_LOAD_ERROR',
  PLAN_SCHEMA_REF_ERROR: 'PLAN_SCHEMA_REF_ERROR',
  PLAN_SEMANTIC_INVALID: 'PLAN_SEMANTIC_INVALID',
  PLAN_HASH_FAILED: 'PLAN_HASH_FAILED',
} as const;

/** LockGate reason codes. */
export const LOCK_REASON_CODES = {
  LOCK_PASS: 'LOCK_PASS',
  LOCK_CREATED: 'LOCK_CREATED',
  MISSING_PLAN_LOCK: 'MISSING_PLAN_LOCK',
  PLAN_LOCK_PARSE_ERROR: 'PLAN_LOCK_PARSE_ERROR',
  PLAN_LOCK_VERSION_MISMATCH: 'PLAN_LOCK_VERSION_MISMATCH',
  PLAN_ID_MISMATCH: 'PLAN_ID_MISMATCH',
  PLAN_LOCK_HASH_MISMATCH: 'PLAN_LOCK_HASH_MISMATCH',
  CRITERIA_CHANGED_AFTER_LOCK: 'CRITERIA_CHANGED_AFTER_LOCK',
  ARTIFACT_POLICY_CHANGED_AFTER_LOCK: 'ARTIFACT_POLICY_CHANGED_AFTER_LOCK',
  INTEGRATION_CONTRACT_CHANGED_AFTER_LOCK: 'INTEGRATION_CONTRACT_CHANGED_AFTER_LOCK',
  COMMAND_POLICY_CHANGED_AFTER_LOCK: 'COMMAND_POLICY_CHANGED_AFTER_LOCK',
  ALLOWED_FILES_CHANGED_AFTER_LOCK: 'ALLOWED_FILES_CHANGED_AFTER_LOCK',
  FORBIDDEN_FILES_CHANGED_AFTER_LOCK: 'FORBIDDEN_FILES_CHANGED_AFTER_LOCK',
  LOCK_HASH_FIELD_MISSING: 'LOCK_HASH_FIELD_MISSING',
} as const;

/** Map PlanHashes field keys to LockGate mismatch reason codes. */
export const HASH_FIELD_REASON_MAP: Record<keyof import('@praxis/contracts').PlanHashes, string> = {
  planHash: LOCK_REASON_CODES.PLAN_LOCK_HASH_MISMATCH,
  acceptanceCriteriaHash: LOCK_REASON_CODES.CRITERIA_CHANGED_AFTER_LOCK,
  artifactPolicyHash: LOCK_REASON_CODES.ARTIFACT_POLICY_CHANGED_AFTER_LOCK,
  integrationContractHash: LOCK_REASON_CODES.INTEGRATION_CONTRACT_CHANGED_AFTER_LOCK,
  commandPolicyHash: LOCK_REASON_CODES.COMMAND_POLICY_CHANGED_AFTER_LOCK,
  allowedFilesHash: LOCK_REASON_CODES.ALLOWED_FILES_CHANGED_AFTER_LOCK,
  forbiddenFilesHash: LOCK_REASON_CODES.FORBIDDEN_FILES_CHANGED_AFTER_LOCK,
};

/** Create a timestamp string for gate verdicts. */
export function now(): string {
  return new Date().toISOString();
}

/** EvidenceGate reason codes. */
export const EVIDENCE_REASON_CODES = {
  // PASS
  EVIDENCE_PASS: 'EVIDENCE_PASS',
  // HOLD
  EVIDENCE_LEDGER_MISSING: 'EVIDENCE_LEDGER_MISSING',
  DIFF_EMPTY: 'DIFF_EMPTY',
  REQUIRED_EVIDENCE_TYPE_MISSING: 'REQUIRED_EVIDENCE_TYPE_MISSING',
  CRITERION_EVIDENCE_MISSING: 'CRITERION_EVIDENCE_MISSING',
  DETERMINISTIC_EVIDENCE_MISSING: 'DETERMINISTIC_EVIDENCE_MISSING',
  EVIDENCE_INCOMPLETE: 'EVIDENCE_INCOMPLETE',
  CHANGED_FILES_MISSING: 'CHANGED_FILES_MISSING',
  // FAIL
  EVIDENCE_LEDGER_PARSE_ERROR: 'EVIDENCE_LEDGER_PARSE_ERROR',
  EVIDENCE_VERSION_MISMATCH: 'EVIDENCE_VERSION_MISMATCH',
  ATTEMPT_ID_MISMATCH: 'ATTEMPT_ID_MISMATCH',
  PLAN_ID_MISMATCH: 'PLAN_ID_MISMATCH',
  FORBIDDEN_FILE_CHANGED: 'FORBIDDEN_FILE_CHANGED',
  CHANGED_FILE_OUTSIDE_ALLOWED_FILES: 'CHANGED_FILE_OUTSIDE_ALLOWED_FILES',
  UNKNOWN_TASK_ID: 'UNKNOWN_TASK_ID',
  UNKNOWN_CRITERION_ID: 'UNKNOWN_CRITERION_ID',
  UNSUPPORTED_EVIDENCE_TYPE: 'UNSUPPORTED_EVIDENCE_TYPE',
  DIVERGENCE_DETECTED: 'DIVERGENCE_DETECTED',
  ATTESTATION_FAILED: 'ATTESTATION_FAILED',
} as const;

/** WiringGate reason codes. */
export const WIRING_REASON_CODES = {
  // PASS
  WIRING_PASS: 'WIRING_PASS',
  // FAIL
  DECLARED_UNIT_MISSING: 'DECLARED_UNIT_MISSING',
  EXPORT_SURFACE_MISSING: 'EXPORT_SURFACE_MISSING',
  // HOLD
  EXPORT_NOT_FOUND: 'EXPORT_NOT_FOUND',
  REQUIRED_EXPORT_MISSING: 'REQUIRED_EXPORT_MISSING',
  ENTRYPOINT_NOT_FOUND: 'ENTRYPOINT_NOT_FOUND',
  INTEGRATION_POINT_NOT_FOUND: 'INTEGRATION_POINT_NOT_FOUND',
  EXPECTED_IMPORT_MISSING: 'EXPECTED_IMPORT_MISSING',
  ORPHAN_MODULES_DETECTED: 'ORPHAN_MODULES_DETECTED',
  WIRING_MODE_INCONSISTENT: 'WIRING_MODE_INCONSISTENT',
  WIRING_MODE_DECLARED_BUT_EMPTY: 'WIRING_MODE_DECLARED_BUT_EMPTY',
} as const;

/** ExecGate reason codes. */
export const EXEC_REASON_CODES = {
  // PASS
  EXEC_PASS: 'EXEC_PASS',
  COMMAND_SUCCEEDED: 'COMMAND_SUCCEEDED',
  // FAIL
  COMMAND_NOT_ALLOWED: 'COMMAND_NOT_ALLOWED',
  COMMAND_DENIED: 'COMMAND_DENIED',
  COMMAND_TIMEOUT: 'COMMAND_TIMEOUT',
  WATCH_MODE_DETECTED: 'WATCH_MODE_DETECTED',
  COMMAND_CRASHED: 'COMMAND_CRASHED',
  // HOLD
  POSSIBLE_WATCH_MODE: 'POSSIBLE_WATCH_MODE',
  NO_TESTS_FOUND: 'NO_TESTS_FOUND',
  UNEXPECTED_EXIT_CODE: 'UNEXPECTED_EXIT_CODE',
  EXIT_CODE_NONZERO: 'EXIT_CODE_NONZERO',
  EXPECTED_OUTPUT_MISSING: 'EXPECTED_OUTPUT_MISSING',
  // INFO
  DISCOVERY_COMMAND_CANNOT_SATISFY_FINAL: 'DISCOVERY_COMMAND_CANNOT_SATISFY_FINAL',
} as const;

/** FinalGate reason codes. */
export const FINAL_REASON_CODES = {
  // PASS
  ALL_CRITERIA_MET: 'ALL_CRITERIA_MET',
  CRITERION_PASS: 'CRITERION_PASS',
  FILE_FOUND: 'FILE_FOUND',
  // HOLD
  CRITERIA_PARTIAL: 'CRITERIA_PARTIAL',
  NO_DETERMINISTIC_CRITERIA: 'NO_DETERMINISTIC_CRITERIA',
  PRIOR_GATE_NOT_PASS: 'PRIOR_GATE_NOT_PASS',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_CONTENT_MISMATCH: 'FILE_CONTENT_MISMATCH',
  DIFF_CONTENT_MISSING: 'DIFF_CONTENT_MISSING',
  COMMAND_OUTPUT_MISMATCH: 'COMMAND_OUTPUT_MISMATCH',
  TEST_FAILURES: 'TEST_FAILURES',
  INTEGRATION_CONTRACT_FAILED: 'INTEGRATION_CONTRACT_FAILED',
  STATIC_PATTERN_MISSING: 'STATIC_PATTERN_MISSING',
  CRITERION_NOT_HUMAN_APPROVED: 'CRITERION_NOT_HUMAN_APPROVED',
  NO_CRITERIA_DEFINED: 'NO_CRITERIA_DEFINED',
  NOT_EVALUATED: 'NOT_EVALUATED',
  // FAIL
  CRITERIA_FAILED: 'CRITERIA_FAILED',
  FORBIDDEN_DIFF_CONTENT: 'FORBIDDEN_DIFF_CONTENT',
  SCHEMA_VALIDATION_FAILED: 'SCHEMA_VALIDATION_FAILED',
  // INFO
  ADVISORY_CRITERION: 'ADVISORY_CRITERION',
  MANUAL_REVIEW_REQUIRED: 'MANUAL_REVIEW_REQUIRED',
} as const;

/** Build a kernel diagnostic. */
export function kdiag(
  code: string,
  severity: DiagnosticSeverity,
  message: string,
): Diagnostic {
  return { code, severity, message } as Diagnostic;
}
